/* =============================================
   DADOS MOCKADOS — Central do Tênis GYN
   ============================================= */

const produtos = [
  // ── MASCULINO ──
  { id:1, nome:"Nike Air Max 270", marca:"Nike", categoria:"casual", genero:"masculino", preco:599.90, desconto:0, tamanhos:[38,39,40,41,42,43], esgotados:[], cor:"#1565C0", corNome:"Azul Royal", tag:"MAIS VENDIDO", novo:false, descricao:"O Nike Air Max 270 oferece o maior Air Max de calcanhar já criado para uso diário. Design atraente com amortecimento excepcional.", especificacoes:{solado:"Borracha",cabedal:"Mesh Engenheirado",forro:"Tecido sintético",palmilha:"EVA removível",drop:"10mm"} },
  { id:2, nome:"Adidas Ultraboost 22", marca:"Adidas", categoria:"corrida", genero:"masculino", preco:749.90, desconto:10, tamanhos:[38,39,40,41,42,43,44], esgotados:[41], cor:"#0D0D0D", corNome:"Preto Noite", tag:"OFERTA", novo:false, descricao:"Tecnologia BOOST para retorno de energia incrível e cabedal Primeknit+ que se adapta ao seu pé.", especificacoes:{solado:"Continental™ Rubber",cabedal:"Primeknit+",forro:"Lycra",palmilha:"BOOST™",drop:"10mm"} },
  { id:3, nome:"New Balance 574", marca:"New Balance", categoria:"casual", genero:"masculino", preco:479.90, desconto:0, tamanhos:[37,38,39,40,41,42,43], esgotados:[], cor:"#2E7D32", corNome:"Verde Militar", tag:"CLÁSSICO", novo:false, descricao:"Um ícone do streetwear mundial. O 574 combina estilo retrô com conforto moderno para o dia a dia.", especificacoes:{solado:"Borracha",cabedal:"Camurça/Mesh",forro:"Tecido",palmilha:"ENCAP",drop:"8mm"} },
  { id:4, nome:"Nike Pegasus 42", marca:"Nike", categoria:"corrida", genero:"masculino", preco:689.90, desconto:5, tamanhos:[38,39,40,41,42,43,44], esgotados:[], cor:"#FF6F00", corNome:"Laranja Fogo", tag:"LANÇAMENTO", novo:true, descricao:"O Nike Pegasus 42 continua a herança de 40 anos da série com React + Air no calcanhar para corridas diárias.", especificacoes:{solado:"Borracha",cabedal:"Flyknit",forno:"Mesh respirável",palmilha:"React + Air",drop:"10mm"} },
  { id:5, nome:"Adidas Samba OG", marca:"Adidas", categoria:"casual", genero:"masculino", preco:529.90, desconto:0, tamanhos:[38,39,40,41,42,43], esgotados:[], cor:"#F5F5F5", corNome:"Branco/Preto", tag:"TREND", novo:false, descricao:"O lendário Samba, nascido nas quadras de futsal nos anos 50, hoje é o tênis mais desejado do streetwear global.", especificacoes:{solado:"Borracha",cabedal:"Couro",forro:"Couro",palmilha:"OrthoLite",drop:"6mm"} },
  { id:6, nome:"Puma RS-X³", marca:"Puma", categoria:"casual", genero:"masculino", preco:419.90, desconto:15, tamanhos:[38,39,40,41,42,43,44], esgotados:[43], cor:"#C62828", corNome:"Vermelho Sport", tag:"OFERTA", novo:false, descricao:"Design chunky com tecnologia RS correndo pelas solas. Bold, colorido e com amortecimento superior.", especificacoes:{solado:"Borracha RS",cabedal:"Mesh+Couro Sintético",forro:"Tecido",palmilha:"RS Foam",drop:"12mm"} },
  { id:7, nome:"ASICS Gel-Kayano 31", marca:"ASICS", categoria:"corrida", genero:"masculino", preco:849.90, desconto:0, tamanhos:[38,39,40,41,42,43,44], esgotados:[], cor:"#4A148C", corNome:"Roxo Performance", tag:"PREMIUM", novo:false, descricao:"O Gel-Kayano 31 oferece suporte superior para pronadores com GEL duplo e plataforma FF Blast+ Eco.", especificacoes:{solado:"AHAR+",cabedal:"Engineered Mesh",forro:"ASICS SmoothBounce",palmilha:"FF Blast+ Eco",drop:"10mm"} },
  { id:8, nome:"Mizuno Wave Prophecy 13", marca:"Mizuno", categoria:"corrida", genero:"masculino", preco:999.90, desconto:0, tamanhos:[38,39,40,41,42,43], esgotados:[], cor:"#006064", corNome:"Teal Premium", tag:"TOP DE LINHA", novo:true, descricao:"O pináculo da tecnologia Mizuno. Wave Plate em carbono proporciona retorno de energia e estabilidade inigualáveis.", especificacoes:{solado:"X10 Carbon Rubber",cabedal:"Premium Mesh",forro:"Premium Lycra",palmilha:"AP+ Midsole + Wave Plate",drop:"12mm"} },
  { id:9, nome:"Vans Old Skool Pro", marca:"Vans", categoria:"casual", genero:"masculino", preco:369.90, desconto:0, tamanhos:[38,39,40,41,42,43,44], esgotados:[], cor:"#212121", corNome:"Preto/Branco", tag:"CLÁSSICO", novo:false, descricao:"A listinha lateral mais icônica do skate. O Old Skool Pro tem sola UltraCush para o máximo de impacto.", especificacoes:{solado:"Waffle",cabedal:"Canvas/Suede",forro:"Tecido",palmilha:"UltraCush",drop:"0mm"} },
  { id:10, nome:"New Balance 1906R", marca:"New Balance", categoria:"casual", genero:"masculino", preco:699.90, desconto:8, tamanhos:[38,39,40,41,42,43], esgotados:[], cor:"#37474F", corNome:"Cinza Metálico", tag:"TREND", novo:true, descricao:"O 1906R revisita a era dourada do running dos anos 2000 com amortecimento ABZORB e visual retrô-futuro.", especificacoes:{solado:"ABZORB+FantomFit",cabedal:"Mesh Técnico",forro:"Mesh",palmilha:"ABZORB",drop:"8mm"} },
  { id:11, nome:"Fila Disruptor II", marca:"Fila", categoria:"casual", genero:"masculino", preco:349.90, desconto:20, tamanhos:[38,39,40,41,42,43,44], esgotados:[], cor:"#FFFFFF", corNome:"Branco Total", tag:"OFERTA", novo:false, descricao:"O chunky mais clássico da Fila. Sola dentada, perfil bold e estilo 90s que nunca sai de moda.", especificacoes:{solado:"EVA Chunky",cabedal:"Couro Sintético",forno:"Tecido",palmilha:"Memory Foam",drop:"14mm"} },
  { id:12, nome:"Nike Air Jordan 1 Retro", marca:"Nike", categoria:"casual", genero:"masculino", preco:1199.90, desconto:0, tamanhos:[38,39,40,41,42,43,44], esgotados:[42,43], cor:"#B71C1C", corNome:"Chicago Red", tag:"EXCLUSIVO", novo:false, descricao:"O original. A lenda. O Air Jordan 1 redefiniu o que um tênis de basquete podia ser — e ainda redefine.", especificacoes:{solado:"Borracha",cabedal:"Couro",forro:"Tecido",palmilha:"Air-Sole",drop:"14mm"} },

  // ── FEMININO ──
  { id:13, nome:"Nike Air Max Pulse", marca:"Nike", categoria:"casual", genero:"feminino", preco:649.90, desconto:0, tamanhos:[34,35,36,37,38,39], esgotados:[], cor:"#F06292", corNome:"Rosa Neon", tag:"LANÇAMENTO", novo:true, descricao:"O Air Max Pulse celebra a cultura musical com design inspirado na cena underground londrina. Vibrante e poderoso.", especificacoes:{solado:"Borracha",cabedal:"Mesh estruturado",forro:"Foam",palmilha:"Air Max",drop:"10mm"} },
  { id:14, nome:"Adidas Stan Smith W", marca:"Adidas", categoria:"casual", genero:"feminino", preco:459.90, desconto:0, tamanhos:[34,35,36,37,38,39,40], esgotados:[], cor:"#FFFFFF", corNome:"Branco/Verde", tag:"CLÁSSICO", novo:false, descricao:"O tênis mais vendido da história do tênis. Elegante, limpo e versátil — combina com tudo.", especificacoes:{solado:"Borracha",cabedal:"Couro",forno:"Tecido",palmilha:"OrthoLite",drop:"6mm"} },
  { id:15, nome:"New Balance 327 W", marca:"New Balance", categoria:"casual", genero:"feminino", preco:499.90, desconto:10, tamanhos:[34,35,36,37,38,39], esgotados:[36], cor:"#CE93D8", corNome:"Lilás Pastel", tag:"TREND", novo:true, descricao:"Silhueta retrô dos anos 70 com cores pastel que dominam o street style feminino atual.", especificacoes:{solado:"Borracha",cabedal:"Mesh+Camurça",forro:"Tecido",palmilha:"ENCAP",drop:"8mm"} },
  { id:16, nome:"Nike Free Run 5.0 W", marca:"Nike", categoria:"corrida", genero:"feminino", preco:549.90, desconto:0, tamanhos:[34,35,36,37,38,39,40], esgotados:[], cor:"#80DEEA", corNome:"Aqua Fresh", tag:"CORRIDA", novo:false, descricao:"Movimento natural e liberdade. A sola flexível do Free Run simula a corrida descalça com proteção total.", especificacoes:{solado:"Flex Grooves",cabedal:"Flyknit",forno:"Mesh",palmilha:"Foam Midsole",drop:"4mm"} },
  { id:17, nome:"Puma Mayze Leather W", marca:"Puma", categoria:"casual", genero:"feminino", preco:389.90, desconto:15, tamanhos:[34,35,36,37,38,39], esgotados:[], cor:"#FFCA28", corNome:"Amarelo Butter", tag:"OFERTA", novo:false, descricao:"Plataforma elevada com cabedal em couro premium. O Mayze é o queridinho do estilo feminino atual.", especificacoes:{solado:"Plataforma EVA",cabedal:"Couro",forno:"Tecido",palmilha:"SoftFoam+",drop:"16mm"} },
  { id:18, nome:"ASICS Gel-Nimbus 25 W", marca:"ASICS", categoria:"corrida", genero:"feminino", preco:879.90, desconto:0, tamanhos:[34,35,36,37,38,39,40], esgotados:[], cor:"#E91E63", corNome:"Rosa Performance", tag:"PREMIUM", novo:false, descricao:"Amortecimento máximo para longas distâncias. O Gel-Nimbus 25 é o companheiro ideal para maratonistas.", especificacoes:{solado:"AHAR Outsole",cabedal:"Engineered Mesh",forno:"ASICS SmoothBounce",palmilha:"FF Blast+",drop:"13mm"} },
  { id:19, nome:"Vans Slip-On W", marca:"Vans", categoria:"casual", genero:"feminino", preco:319.90, desconto:0, tamanhos:[34,35,36,37,38,39], esgotados:[], cor:"#FF8A65", corNome:"Pêssego", tag:"ESTILO", novo:false, descricao:"Fácil de calçar, impossível de tirar. O Slip-On é o ícone de praticidade e estilo que atravessa gerações.", especificacoes:{solado:"Waffle",cabedal:"Canvas",forro:"Tecido",palmilha:"Insole Confortável",drop:"0mm"} },
  { id:20, nome:"Nike Cortez W", marca:"Nike", categoria:"casual", genero:"feminino", preco:429.90, desconto:5, tamanhos:[34,35,36,37,38,39,40], esgotados:[], cor:"#B2DFDB", corNome:"Menta", tag:"TREND", novo:true, descricao:"De volta ao estilo dos anos 70. O Cortez é o retorno triunfal de um clássico Nike que domina o street style 2025.", especificacoes:{solado:"Borracha",cabedal:"Couro+Nylon",forno:"Tecido",palmilha:"EVA",drop:"8mm"} },
  { id:21, nome:"Adidas Gazelle W", marca:"Adidas", categoria:"casual", genero:"feminino", preco:479.90, desconto:0, tamanhos:[34,35,36,37,38,39], esgotados:[], cor:"#7B1FA2", corNome:"Roxo Vintage", tag:"CLÁSSICO", novo:false, descricao:"Nascido nas quadras de esporte nos anos 60, o Gazelle é hoje sinônimo de estilo feminino atemporal.", especificacoes:{solado:"Borracha",cabedal:"Camurça",forno:"Couro",palmilha:"OrthoLite",drop:"6mm"} },
  { id:22, nome:"Mizuno Wave Skyrise 4 W", marca:"Mizuno", categoria:"corrida", genero:"feminino", preco:699.90, desconto:12, tamanhos:[34,35,36,37,38,39,40], esgotados:[37], cor:"#F48FB1", corNome:"Rosa Coral", tag:"CORRIDA", novo:true, descricao:"Leveza e responsividade para treinos diários. O Wave Skyrise entrega velocidade com estabilidade Mizuno.", especificacoes:{solado:"X10",cabedal:"Waveknit",forno:"Lycra",palmilha:"Enerzy Lite",drop:"10mm"} },

  // ── INFANTIL ──
  { id:23, nome:"Nike Downshifter 12 Kids", marca:"Nike", categoria:"corrida", genero:"infantil", preco:249.90, desconto:0, tamanhos:[28,29,30,31,32,33,34], esgotados:[], cor:"#42A5F5", corNome:"Azul Kids", tag:"INFANTIL", novo:false, descricao:"Leve, durável e fácil de calçar. O Downshifter 12 Kids foi feito para aguentar a energia das crianças.", especificacoes:{solado:"Borracha",cabedal:"Mesh",forno:"Sintético",palmilha:"EVA",drop:"10mm"} },
  { id:24, nome:"Adidas Tensaur Run Kids", marca:"Adidas", categoria:"corrida", genero:"infantil", preco:219.90, desconto:10, tamanhos:[28,29,30,31,32,33,34,35], esgotados:[], cor:"#66BB6A", corNome:"Verde Neon Kids", tag:"OFERTA", novo:false, descricao:"Sistema de fechamento fácil para pequenos aventureiros. Respirável e com estabilidade para corridas e brincadeiras.", especificacoes:{solado:"Borracha",cabedal:"Mesh",forno:"Sintético",palmilha:"Cloudfoam",drop:"10mm"} },
  { id:25, nome:"New Balance 680 Kids", marca:"New Balance", categoria:"corrida", genero:"infantil", preco:269.90, desconto:0, tamanhos:[28,29,30,31,32,33,34], esgotados:[], cor:"#FF7043", corNome:"Laranja Kids", tag:"INFANTIL", novo:true, descricao:"O 680 Kids tem bico reforçado e sola de borracha resistente para aguentar todo o desgaste do cotidiano infantil.", especificacoes:{solado:"NDurance Rubber",cabedal:"Mesh",forno:"Mesh",palmilha:"Foam",drop:"10mm"} },
  { id:26, nome:"Puma Anzarun Kids", marca:"Puma", categoria:"casual", genero:"infantil", preco:189.90, desconto:15, tamanhos:[28,29,30,31,32,33,34,35], esgotados:[], cor:"#AB47BC", corNome:"Roxo Kids", tag:"OFERTA", novo:false, descricao:"Design moderno com velcro prático para que as crianças possam calçar e descalçar com independência.", especificacoes:{solado:"Borracha",cabedal:"Mesh",forno:"Tecido",palmilha:"SoftFoam",drop:"8mm"} },
  { id:27, nome:"Vans Old Skool Kids", marca:"Vans", categoria:"casual", genero:"infantil", preco:279.90, desconto:0, tamanhos:[28,29,30,31,32,33,34], esgotados:[], cor:"#37474F", corNome:"Preto/Branco Kids", tag:"CLÁSSICO", novo:false, descricao:"O clássico listinha lateral agora nos pezinhos dos pequenos. O Old Skool Kids é estilo desde cedo.", especificacoes:{solado:"Waffle",cabedal:"Canvas/Suede",forno:"Tecido",palmilha:"Confortável",drop:"0mm"} },
  { id:28, nome:"Nike Revolution 7 Kids", marca:"Nike", categoria:"corrida", genero:"infantil", preco:229.90, desconto:20, tamanhos:[28,29,30,31,32,33,34,35], esgotados:[], cor:"#EF5350", corNome:"Vermelho Kids", tag:"OFERTA", novo:false, descricao:"Leve e colorido. O Revolution 7 Kids combina conforto diário com visual esportivo que as crianças amam.", especificacoes:{solado:"Borracha",cabedal:"Mesh",forno:"Sintético",palmilha:"Foam",drop:"10mm"} },
  { id:29, nome:"Adidas Fortarun Kids", marca:"Adidas", categoria:"corrida", genero:"infantil", preco:199.90, desconto:0, tamanhos:[28,29,30,31,32,33,34], esgotados:[], cor:"#29B6F6", corNome:"Azul Céu Kids", tag:"INFANTIL", novo:true, descricao:"Cloudfoam macio e elástico na lingueta para calçar fácil. Feito para crianças que nunca ficam paradas.", especificacoes:{solado:"Sintético",cabedal:"Mesh",forno:"Mesh",palmilha:"Cloudfoam",drop:"10mm"} },
  { id:30, nome:"ASICS Gel-Contend 8 Kids", marca:"ASICS", categoria:"corrida", genero:"infantil", preco:289.90, desconto:0, tamanhos:[28,29,30,31,32,33,34,35], esgotados:[], cor:"#26A69A", corNome:"Teal Kids", tag:"PREMIUM", novo:false, descricao:"GEL Technology da ASICS em versão kids. Amortecimento de verdade para os pequenos corredores do futuro.", especificacoes:{solado:"AHAR",cabedal:"Engineered Mesh",forno:"Tecido",palmilha:"GEL+EVA",drop:"10mm"} }
];

const marcas = ["Nike","Adidas","New Balance","Puma","Fila","Vans","ASICS","Mizuno"];
const tamanhosList = [37,38,39,40,41,42,43,44];

function getProduto(id) { return produtos.find(p => p.id === id); }
function getNovidades() { return produtos.filter(p => p.novo); }
function calcularPrecoFinal(p) { return p.desconto > 0 ? p.preco * (1 - p.desconto/100) : p.preco; }
function calcularPrecoPix(p) { return calcularPrecoFinal(p) * 0.9; }
function formatarPreco(v) { return "R$ " + v.toFixed(2).replace(".", ",").replace(/\B(?=(\d{3})+(?!\d))/g, "."); }
